theme: minima
title: Schrier's Sudelbücher
description: miscellaneous notes on probability, optimization, geometry, and programming
twitter_username: JoshuaSchrier
github_username:  jschrier
show_excerpts: true
